baseURL = 'https://liveamar.github.io/blog/'
languageCode = 'en-us'
title = 'LiveAmar'

theme = "paper"

disqusShortname = 'LiveAmar'   # use disqus comments

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light


  # home page profile
  avatar = 'https://scontent.fdbd1-1.fna.fbcdn.net/v/t39.30808-6/336192244_574404417981681_5826333750976862255_n.jpg'                 # gravatar email or image url
  name = 'Amar Murmu'
  bio = 'I'm a developer who also enjoys to be creative.'


  # misc
  disableHLJS = true                        # disable highlight.js
  monoDarkIcon = false                       # show monochrome dark mode icon
  graphCommentId = "LiveAmar"  # use graph comment (disqus alternative)

  comments = true                            # disable comments for a specific page